### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by robbisg** [robbisg/pyitab#17]
#### Permutation
- [ ] Is it better to use a transformer? #82 

#### Cross-decoding
- [ ] Build a custom CrossValidator

#### Transformers
- [ ] #85

#### Connectivity
See #60 

#### States
- [ ] Build StateAnalyzer
- [ ] Build Transformers for states
- [ ] Import metrics from mvpa_itab

#### Results
- [ ] Refactor results using BIDS format of derivatives #27 
- [ ] Cope with subject-wise results.

#### Configurator, Pipelines and Iterator
- [x] Create a Configurator class that is general. #30 
- [x] Create a DecodingConfigurator class that inherits from Configurator. #30
- [x] Add Dataset Loading into Configurator #31 
- [x] Study the possibility to use iterator to run subject-wise analysis.

## Deprecated
- [x] Evaluate ```load_spatiotemporal_dataset```
- [ ] Evaluate ```read_configuration_json``` 
- [x] Evaluate ```read_remote_configuration```
